### ISSUE TITLE
"." as phone

### ISSUE THREAD

**Issue by wassname** [timmahrt/pysle#2]
I don't know enough about linguistic to know if "." is a phone but it comes up for some words. In some lines in my dictionary like "pirouette" the entry ends with ". #" leading to "." showing up as a phone. Is this intended?

```python
from pysle import isletool
isleDict = isletool.LexicalTool('../data/isledict/ISLEdict.txt')
isleDict.data["pirouette"]
#> ['# p ˌɪ . ɹ u . ˈɛ̃ . #', '# p ˌɪ . ɹ u . ˈɛ̃ t #']
isleDict.lookup('pirouette')
#> [([['p', 'ˌɪ'], ['ɹ', 'u'], ['ˈɛ̃', '.']], [2, 0], [0, 1]),
#> ([['p', 'ˌɪ'], ['ɹ', 'u'], ['ˈɛ̃', 't']], [2, 0], [0, 1])]
```

**Comment by timmahrt** [comment]
So a "." is a syllable boundary and a "#" is a word boundary.  It doesn't make sense to have the sequence ". #" or "# .".  I wondered if maybe this had some special significance but looking through the ISLEdict, there are only 4 entries like this--I believe it is an error and have reported it to the ISLEdict maintainers.

For now, my recommendation is to delete the final '.' in these four entries.

	Line 191096: pirouette(nn,vb) # p ˌɪ . ɹ u . ˈɛ̃ . #
	Line 248111: tais() # t ˌɑɪ z . #
	Line 258722: treichel(nnp_surname_0.000) # t ɹ ˈɑɪ . k ə . #
	Line 281100: yipes() # j ˌɑɪ p z . #

**Comment by timmahrt** [comment]
Also, for clarification, there are no entries that contain the sequence '# .'

**Comment by timmahrt** [comment]
Ok, this issue is patched as of.  In the new code, an empty syllable will appear in these situations, since that is essentially what it is.  The maintainer of ISLEdict also said the four entries would be corrected.

[Patch](https://github.com/timmahrt/pysle/commit/e47ab5630679451b719787f5579968756bd7a644)

**Comment by wassname** [comment]
That makes sense, thanks for looking into that and explaining
