### ISSUE TITLE
'ɛ̃' missing as vowel in isletool

### ISSUE THREAD

**Issue by mcmahanp** [timmahrt/pysle#4]
the vowel sound 'ɛ̃' is not accounted for in the search functionality of isletool.

This means that a search like:
`isleDict.search("",numSyllables=2,multiword='no',stressedSyllable='only',wordInitial='only')`
should include `('welder', ['# w ˈɛ̃ l . d ɚ #'])` but it does not (unless I'm misunderstanding something?)

I was able to fix it for my needs by adding 'ɛ̃' to `isletool.charList` and `isletool.vowelList`, and changing line 211 of isletool.py to:

    "V": u"(?:aʊ|ei|oʊ|ɑɪ|ɔi|[iuæɑɔəɛɪʊʌɛ̃]):?",  # vowels

**Comment by timmahrt** [comment]
When I run the search you posted:
isleDict.search("",numSyllables=2,multiword='no',stressedSyllable='only',wordInitial='only')

'welder' was in the results.  Are you sure that you ran that exact search?

**Comment by timmahrt** [comment]
Also, 'ɛ̃' does not appear in English.  There are only instances of 'ɛ̃' and none of 'ɛ' in the isledict.  I'm assuming this is a mistake but I am contacting the maintainer to get their thoughts on the issue.

I believe it is safe for you to do a search and replace all of ɛ̃ with ɛ.

Hidden in plain sight.  Thanks for bringing this to my attention!

I'd still be interested in the query you ran that did not yield 'welder' when it should have--that might indicate the presence of a bug that goes deeper than just ɛ̃/ɛ.

**Comment by mcmahanp** [comment]
My mistake! I thought I had checked pretty carefully here for words like 'welder', 'elder', etc., but when I reran from scratch they were all in there as expected.

However this did bring up a further issue, where I was categorizing words by their initial vowel sound and was using `isletool.vowelList` as the list of possible sounds. Since 'ɛ̃' isn't in that list I was missing a whole bunch of words in my final categorization. It sounds like this has to do with the 'ɛ̃'/'ɛ' issue you mentioned, so I'm not sure if it's better to amend `vowelList` and `charList` or to fix the isledict :)

In any case, it's working great for me if I amend the list just in my project, so I'm happy.

Thanks for putting this tool together! It has been very useful!

**Comment by timmahrt** [comment]
I contacted the maintainer of the isle dict, Prof. Mark Hasegawa-Johnson.  He agreed that ɛ̃ should not be in the isledict--he changed every instance of ɛ̃ to ɛ.  Keep this in mind if you download a new version of the isledict.

I'm closing this bug report now.  If you find any other bugs, please let me know!

Thanks!
