### ISSUE TITLE
No attribute 'isletool'

### ISSUE THREAD

**Issue by PasaOpasen** [timmahrt/pysle#6]
Let's see:
```

import pysle

pysle.isletool.LexicalTool.lookup('cat')
Traceback (most recent call last):

  File "<ipython-input-1-09f456e372af>", line 3, in <module>
    pysle.isletool.LexicalTool.lookup('cat')

AttributeError: module 'pysle' has no attribute 'isletool'


from pysle import isle
Traceback (most recent call last):

  File "<ipython-input-2-23a7e2ed01cb>", line 1, in <module>
    from pysle import isle

ImportError: cannot import name 'isle' from 'pysle' (C:\ProgramData\Anaconda3\lib\site-packages\pysle\__init__.py)


from pysle import pronunciationTools
Traceback (most recent call last):

  File "<ipython-input-3-23b867baacbb>", line 1, in <module>
    from pysle import pronunciationTools

ImportError: cannot import name 'pronunciationTools' from 'pysle' (C:\ProgramData\Anaconda3\lib\site-packages\pysle\__init__.py)
```

**Comment by timmahrt** [comment]
Hello,
I'm sorry for the headaches.

```
import pysle
pysle.isletool.LexicalTool.lookup('cat')
```
When importing the main library, I don't import in related files in `__init__.py`.  submodules should be imported independently.  I don't know if this is a good thing or bad thing.  If you have comments please share.  In this case, you should write `from pysle import isletool`

```
from pysle import isle
```
There is no module called `isle`.  Did you mean `isletool`?

```
from pysle import pronunciationTools
```

To work, it should be `pronunciationtools`.

If you are trying to use this library, you can find some working examples in the `examples` subfolder.  If you have any thoughts on improvements, please let me know.

Thank you!

**Comment by PasaOpasen** [comment]
Okay, it's typos in readme

**Comment by timmahrt** [comment]
Ah!  I'm sorry, I should update the readme.  Also, I see that some of the code doesn't work.  I will fix it!

**Comment by timmahrt** [comment]
I've updated the readme file and some of the doc strings.  I generated some documentation too
http://timmahrt.github.io/pysle/

I fixed the behaviour in one of the functions.

Sorry again!  I'll close this ticket but feel free to open it if you find more problems.
