### ISSUE TITLE
no dictionary

### ISSUE THREAD

**Issue by PasaOpasen** [timmahrt/pysle#8]
```
from pysle import isletool

isletool.LexicalTool('ISLEdict.txt').lookup('cat')
```

I think u should point all data files into [MANIFEST.in](https://github.com/PasaOpasen/PersianG2P/blob/master/MANIFEST.in) file 

See https://realpython.com/pypi-publish-python-package/ 

I do something like for persian language: https://github.com/PasaOpasen/PersianG2P

**Comment by timmahrt** [comment]
The dictionary is not licensed, so I don't think I can include it in my library.  I had a similar problem with my praatio library.

**Comment by PasaOpasen** [comment]
But u can convert this file into dictionary python object and save as python object or as json. It will work faster and will be better to upload

**Comment by PasaOpasen** [comment]
Sorry, I forgot to add the error message:

```
Traceback (most recent call last):

  File "<ipython-input-1-c4a023343ec3>", line 3, in <module>
    isletool.LexicalTool('ISLEdict.txt').lookup('cat')

  File "C:\ProgramData\Anaconda3\lib\site-packages\pysle\isletool.py", line 74, in __init__
    self.data = self._buildDict()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pysle\isletool.py", line 81, in _buildDict
    with io.open(self.islePath, "r", encoding='utf-8') as fd:

FileNotFoundError: [Errno 2] No such file or directory: 'ISLEdict.txt'
```

**Comment by timmahrt** [comment]
As I said, the issue of including it is a legal one.  Perhaps I can ask if the data can be released under some license?

Either way, maybe I could cache the results or store in some intermediate format to make loading faster.

**Comment by PasaOpasen** [comment]
So how should I use this package without necessary data?

It will be very good if u convert necessary files into some json/binary formats to not have legacy problems

**Comment by timmahrt** [comment]
Oh sorry, it's in the requirements section:
https://raw.githubusercontent.com/uiuc-sst/g2ps/master/English/ISLEdict.txt

The data is derived from an academic project.

If there is a way for me to make that clearer, please let me know.

**Comment by timmahrt** [comment]
I have made a new release 2.1.1  If you try to load the ISLEdict but it does not exist, a warning states where to find the file:

```python
>>> from pysle import isletool
>>> a = isletool.LexicalTool('bloop.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "isletool.py", line 87, in __init__
    raise IsleDictDoesNotExist()
pysle.isletool.IsleDictDoesNotExist: The path to the ISLE dictionary file does not exist.
The ISLE dictionary is an external resource that must  be downloaded separately.  ISLEdict.txt can be found here:
https://github.com/uiuc-sst/g2ps/tree/master/English/ISLEdict.txt
Please see the requirements section in the README file for more details.
```
What do you think?

It takes about 1~1.5 seconds to load ISLEDict.txt into memory.  If we pickle the data and then load it, it takes about the same amount of time.  I was a bit surprised.  Maybe I did something wrong?

**Comment by timmahrt** [comment]
I also tried serializing/deserializing with json and it wasn't any faster.  I think it is slow to load simply because the dictionary file is large (~16 MB).

**Comment by PasaOpasen** [comment]
Okay, now I know the path to dictionaries, thank u. I will try to use it.

So will ur package work with another languages if I use it's dictionary?

With my project I have saved my dictionary (50kb) into json and the loading of this was over 5 times faster

**Comment by timmahrt** [comment]
Unfortunately, I don't know of a similar resource file for other languages.  If you know of any, please share!

**Comment by PasaOpasen** [comment]
So I found [this collection](https://github.com/kylebgorman/wikipron/tree/master/data/wikipron). Is it exactly ur package need?

**Comment by timmahrt** [comment]
That collection is useful but actually it comes with its own python code.  I think if you want to access the wikipron dataset, you should use their python library:
```
https://github.com/kylebgorman/wikipron
```

If you need languages other than English, you should use wikipron.

If you only need English, ISLEdict has 10 times as many words and includes syllable information. wikipron does not include syllable boundaries.

**Comment by sevagh** [comment]
The upstream project is now MIT licensed. Perhaps that means the file can now be included in this repo? https://github.com/uiuc-sst/g2ps/commit/8abb736ab4d200caefa31ce69f610e6aa63f59b5

**Comment by timmahrt** [comment]
Nice find!  I should be able to put out a release with it included today or tomorrow.  Thanks!

**Comment by timmahrt** [comment]
Release v.2.2.0 is out.  You can now just do:
```
from pysle import isletool
isleDict = isletool.LexicalTool()
isleDict.lookup('pumpkin')
```
etc

Thanks!
